name: docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Install Vercel CLI
      run: npm install -g vercel@37.8.0

    - name: Deploy to vercel
      uses: BetaHuhn/deploy-to-vercel-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    - name: Typesense scraper
      uses: celsiusnarhwal/typesense-scraper@v2
      with:
        api-key: ${{ secrets.TYPESENSE_API_KEY }}
        host: search.solidcharts.dev
        port: 443
        protocol: https
        config: ./docs/typesense.config.json
